### ISSUE TITLE
capabilities.find returns NoneType

### ISSUE THREAD

**Issue by cefect** [marcusmohr/simplewcs2#7]
Getting the below error when trying [this url](https://datacube.services.geo.ca/ows/elevation) (on all wcs versions):

`WARNING    Traceback (most recent call last):
              File "C:/Users/cefect/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\simplewcs2\simplewcs.py", line 176, in getCapabilities
              self.wcs = WCS(capabilities)
              File "C:/Users/cefect/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\simplewcs2\wcs.py", line 24, in __init__
              self.describeCoverageUrl = self.capabilities.find(ows + 'OperationsMetadata/' + ows + 'Operation[@name="DescribeCoverage"]/' + ows + 'DCP/' + ows + 'HTTP/' + ows + 'Get').attrib[xlink + 'href']
             AttributeError: 'NoneType' object has no attribute 'attrib'`

I'm guessing something is wrong with the server? but the error message doesn't help at all.

![image](https://user-images.githubusercontent.com/47092034/112545139-764b3200-8d7d-11eb-9243-09b906301a5b.png)

**Comment by marcusmohr** [comment]
The WCS only supports version 1.1.1 and not version 2 or higher. Maybe the error message should be clearer.
